version: 0.2
env:
    secrets-manager:
      TOKEN: brazilsecret:tokenForSonarbr
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=eddythatechie -Dsonar.organization=eddythatechie -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
      - sleep 5
      - |
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=eddythatechie | jq -r '.projectStatus.status')
        echo "SonarCloud analysis status is $quality_status"; 
        if [ "$quality_status" = "ERROR" ]; then exit 1; fi
      - apt-get update && apt-get -y install wget default-jdk
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
      - tar -xvf ZAP_2.14.0_Linux.tar.gz
      - cd ZAP_2.14.0
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html
artifacts:
  files:
    - zap_report.html
